class CreateCountries < ActiveRecord::Migration[7.0]
  def change
    create_table :countries do |t|
      t.string :sortname
      t.string :name

      t.timestamps
    end

    Country.create([
      { sortname: 'AF', name: 'Afghanistan' },
      { sortname: 'AL', name: 'Albania' },
      { sortname: 'DZ', name: 'Algeria' },
      { sortname: 'AS', name: 'American Samoa' },
      { sortname: 'AD', name: 'Andorra' },
      { sortname: 'AO', name: 'Angola' },
      { sortname: 'AI', name: 'Anguilla' },
      { sortname: 'AQ', name: 'Antarctica' },
      { sortname: 'AG', name: 'Antigua And Barbuda' },
      { sortname: 'AR', name:  'Argentina' },
      { sortname: 'AM', name:  'Armenia' },
      { sortname: 'AW', name:  'Aruba' },
      { sortname: 'AU', name:  'Australia' },
      { sortname: 'AT', name:  'Austria' },
      { sortname: 'AZ', name:  'Azerbaijan' },
      { sortname: 'BS', name:  'Bahamas The' },
      { sortname: 'BH', name:  'Bahrain' },
      { sortname: 'BD', name:  'Bangladesh' },
      { sortname: 'BB', name:  'Barbados' },
      { sortname: 'BY', name:  'Belarus' },
      { sortname: 'BE', name:  'Belgium' },
      { sortname: 'BZ', name:  'Belize' },
      { sortname: 'BJ', name:  'Benin' },
      { sortname: 'BM', name:  'Bermuda' },
      { sortname: 'BT', name:  'Bhutan' },
      { sortname: 'BO', name:  'Bolivia' },
      { sortname: 'BA', name:  'Bosnia and Herzegovina' },
      { sortname: 'BW', name:  'Botswana' },
      { sortname: 'BV', name:  'Bouvet Island' },
      { sortname: 'BR', name:  'Brazil' },
      { sortname: 'IO', name:  'British Indian Ocean Territory' },
      { sortname: 'BN', name:  'Brunei' },
      { sortname: 'BG', name:  'Bulgaria' },
      { sortname: 'BF', name:  'Burkina Faso' },
      { sortname: 'BI', name:  'Burundi' },
      { sortname: 'KH', name:  'Cambodia' },
      { sortname: 'CM', name:  'Cameroon' },
      { sortname: 'CA', name:  'Canada' },
      { sortname: 'CV', name:  'Cape Verde' },
      { sortname: 'KY', name:  'Cayman Islands' },
      { sortname: 'CF', name:  'Central African Republic' },
      { sortname: 'TD', name:  'Chad' },
      { sortname: 'CL', name:  'Chile' },
      { sortname: 'CN', name:  'China' },
      { sortname: 'CX', name:  'Christmas Island' },
      { sortname: 'CC', name:  'Cocos (Keeling) Islands' },
      { sortname: 'CO', name:  'Colombia' },
      { sortname: 'KM', name:  'Comoros' },
      { sortname: 'CG', name:  'Congo' },
      { sortname: 'CD', name:  'Congo The Democratic Republic Of The' },
      { sortname: 'CK', name:  'Cook Islands' },
      { sortname: 'CR', name:  'Costa Rica' },
      { sortname: 'CI', name:  'Cote D\'Ivoire (Ivory Coast)' },
      { sortname: 'HR', name:  'Croatia (Hrvatska)' },
      { sortname: 'CU', name:  'Cuba' },
      { sortname: 'CY', name:  'Cyprus' },
      { sortname: 'CZ', name:  'Czech Republic' },
      { sortname: 'DK', name:  'Denmark' },
      { sortname: 'DJ', name:  'Djibouti' },
      { sortname: 'DM', name:  'Dominica' },
      { sortname: 'DO', name:  'Dominican Republic' },
      { sortname: 'TP', name:  'East Timor' },
      { sortname: 'EC', name:  'Ecuador' },
      { sortname: 'EG', name:  'Egypt' },
      { sortname: 'SV', name:  'El Salvador' },
      { sortname: 'GQ', name:  'Equatorial Guinea' },
      { sortname: 'ER', name:  'Eritrea' },
      { sortname: 'EE', name:  'Estonia' },
      { sortname: 'ET', name:  'Ethiopia' },
      { sortname: 'XA', name:  'External Territories of Australia' },
      { sortname: 'FK', name:  'Falkland Islands' },
      { sortname: 'FO', name:  'Faroe Islands' },
      { sortname: 'FJ', name:  'Fiji Islands' },
      { sortname: 'FI', name:  'Finland' },
      { sortname: 'FR', name:  'France' },
      { sortname: 'GF', name:  'French Guiana' },
      { sortname: 'PF', name:  'French Polynesia' },
      { sortname: 'TF', name:  'French Southern Territories' },
      { sortname: 'GA', name:  'Gabon' },
      { sortname: 'GM', name:  'Gambia The' },
      { sortname: 'GE', name:  'Georgia' },
      { sortname: 'DE', name:  'Germany' },
      { sortname: 'GH', name:  'Ghana' },
      { sortname: 'GI', name:  'Gibraltar' },
      { sortname: 'GR', name:  'Greece' },
      { sortname: 'GL', name:  'Greenland' },
      { sortname: 'GD', name:  'Grenada' },
      { sortname: 'GP', name:  'Guadeloupe' },
      { sortname: 'GU', name:  'Guam' },
      { sortname: 'GT', name:  'Guatemala' },
      { sortname: 'XU', name:  'Guernsey and Alderney' },
      { sortname: 'GN', name:  'Guinea' },
      { sortname: 'GW', name:  'Guinea-Bissau' },
      { sortname: 'GY', name:  'Guyana' },
      { sortname: 'HT', name:  'Haiti' },
      { sortname: 'HM', name:  'Heard and McDonald Islands' },
      { sortname: 'HN', name:  'Honduras' },
      { sortname: 'HK', name:  'Hong Kong S.A.R.' },
      { sortname: 'HU', name:  'Hungary' },
      { sortname: 'IS', name: 'Iceland' },
      { sortname: 'IN', name: 'India' },
      { sortname: 'ID', name: 'Indonesia' },
      { sortname: 'IR', name: 'Iran' },
      { sortname: 'IQ', name: 'Iraq' },
      { sortname: 'IE', name: 'Ireland' },
      { sortname: 'IL', name: 'Israel' },
      { sortname: 'IT', name: 'Italy' },
      { sortname: 'JM', name: 'Jamaica' },
      { sortname: 'JP', name: 'Japan' },
      { sortname: 'XJ', name: 'Jersey' },
      { sortname: 'JO', name: 'Jordan' },
      { sortname: 'KZ', name: 'Kazakhstan' },
      { sortname: 'KE', name: 'Kenya' },
      { sortname: 'KI', name: 'Kiribati' },
      { sortname: 'KP', name: 'Korea North' },
      { sortname: 'KR', name: 'Korea South' },
      { sortname: 'KW', name: 'Kuwait' },
      { sortname: 'KG', name: 'Kyrgyzstan' },
      { sortname: 'LA', name: 'Laos' },
      { sortname: 'LV', name: 'Latvia' },
      { sortname: 'LB', name: 'Lebanon' },
      { sortname: 'LS', name: 'Lesotho' },
      { sortname: 'LR', name: 'Liberia' },
      { sortname: 'LY', name: 'Libya' },
      { sortname: 'LI', name: 'Liechtenstein' },
      { sortname: 'LT', name: 'Lithuania' },
      { sortname: 'LU', name: 'Luxembourg' },
      { sortname: 'MO', name: 'Macau S.A.R.' },
      { sortname: 'MK', name: 'Macedonia' },
      { sortname: 'MG', name: 'Madagascar' },
      { sortname: 'MW', name: 'Malawi' },
      { sortname: 'MY', name: 'Malaysia' },
      { sortname: 'MV', name: 'Maldives' },
      { sortname: 'ML', name: 'Mali' },
      { sortname: 'MT', name: 'Malta' },
      { sortname: 'XM', name: 'Man (Isle of)' },
      { sortname: 'MH', name: 'Marshall Islands' },
      { sortname: 'MQ', name:  'Martinique' },
      { sortname: 'MR', name:  'Mauritania' },
      { sortname: 'MU', name:  'Mauritius' },
      { sortname: 'YT', name:  'Mayotte' },
      { sortname: 'MX', name:  'Mexico' },
      { sortname: 'FM', name:  'Micronesia' },
      { sortname: 'MD', name:  'Moldova' },
      { sortname: 'MC', name:  'Monaco' },
      { sortname: 'MN', name:  'Mongolia' },
      { sortname: 'MS', name:  'Montserrat' },
      { sortname: 'MA', name:  'Morocco' },
      { sortname: 'MZ', name:  'Mozambique' },
      { sortname: 'MM', name:  'Myanmar' },
      { sortname: 'NA', name:  'Namibia' },
      { sortname: 'NR', name:  'Nauru' },
      { sortname: 'NP', name:  'Nepal' },
      { sortname: 'AN', name:  'Netherlands Antilles' },
      { sortname: 'NL', name:  'Netherlands The' },
      { sortname: 'NC', name:  'New Caledonia' },
      { sortname: 'NZ', name:  'New Zealand' },
      { sortname: 'NI', name:  'Nicaragua' },
      { sortname: 'NE', name:  'Niger' },
      { sortname: 'NG', name:  'Nigeria' },
      { sortname: 'NU', name:  'Niue' },
      { sortname: 'NF', name:  'Norfolk Island' },
      { sortname: 'MP', name:  'Northern Mariana Islands' },
      { sortname: 'NO', name:  'Norway' },
      { sortname: 'OM', name:  'Oman' },
      { sortname: 'PK', name:  'Pakistan' },
      { sortname: 'PW', name:  'Palau' },
      { sortname: 'PS', name:  'Palestinian Territory Occupied' },
      { sortname: 'PA', name:  'Panama' },
      { sortname: 'PG', name:  'Papua new Guinea' },
      { sortname: 'PY', name:  'Paraguay' },
      { sortname: 'PE', name:  'Peru' },
      { sortname: 'PH', name:  'Philippines' },
      { sortname: 'PN', name:  'Pitcairn Island' },
      { sortname: 'PL', name:  'Poland' },
      { sortname: 'PT', name:  'Portugal' },
      { sortname: 'PR', name:  'Puerto Rico' },
      { sortname: 'QA', name:  'Qatar' },
      { sortname: 'RE', name:  'Reunion' },
      { sortname: 'RO', name:  'Romania' },
      { sortname: 'RU', name:  'Russia' },
      { sortname: 'RW', name:  'Rwanda' },
      { sortname: 'SH', name:  'Saint Helena' },
      { sortname: 'KN', name:  'Saint Kitts And Nevis' },
      { sortname: 'LC', name:  'Saint Lucia' },
      { sortname: 'PM', name:  'Saint Pierre and Miquelon' },
      { sortname: 'VC', name:  'Saint Vincent And The Grenadines' },
      { sortname: 'WS', name:  'Samoa' },
      { sortname: 'SM', name:  'San Marino' },
      { sortname: 'ST', name:  'Sao Tome and Principe' },
      { sortname: 'SA', name:  'Saudi Arabia' },
      { sortname: 'SN', name:  'Senegal' },
      { sortname: 'RS', name:  'Serbia' },
      { sortname: 'SC', name:  'Seychelles' },
      { sortname: 'SL', name:  'Sierra Leone' },
      { sortname: 'SG', name:  'Singapore' },
      { sortname: 'SK', name:  'Slovakia' },
      { sortname: 'SI', name:  'Slovenia' },
      { sortname: 'XG', name:  'Smaller Territories of the UK' },
      { sortname: 'SB', name:  'Solomon Islands' },
      { sortname: 'SO', name:  'Somalia' },
      { sortname: 'ZA', name:  'South Africa' },
      { sortname: 'GS', name:  'South Georgia' },
      { sortname: 'SS', name:  'South Sudan' },
      { sortname: 'ES', name:  'Spain' },
      { sortname: 'LK', name:  'Sri Lanka' },
      { sortname: 'SD', name:  'Sudan' },
      { sortname: 'SR', name:  'Suriname' },
      { sortname: 'SJ', name:  'Svalbard And Jan Mayen Islands' },
      { sortname: 'SZ', name:  'Swaziland' },
      { sortname: 'SE', name:  'Sweden' },
      { sortname: 'CH', name:  'Switzerland' },
      { sortname: 'SY', name:  'Syria' },
      { sortname: 'TW', name:  'Taiwan' },
      { sortname: 'TJ', name:  'Tajikistan' },
      { sortname: 'TZ', name:  'Tanzania' },
      { sortname: 'TH', name:  'Thailand' },
      { sortname: 'TG', name:  'Togo' },
      { sortname: 'TK', name:  'Tokelau' },
      { sortname: 'TO', name:  'Tonga' },
      { sortname: 'TT', name:  'Trinidad And Tobago' },
      { sortname: 'TN', name:  'Tunisia' },
      { sortname: 'TR', name:  'Turkey' },
      { sortname: 'TM', name:  'Turkmenistan' },
      { sortname: 'TC', name:  'Turks And Caicos Islands' },
      { sortname: 'TV', name:  'Tuvalu' },
      { sortname: 'UG', name:  'Uganda' },
      { sortname: 'UA', name:  'Ukraine' },
      { sortname: 'AE', name:  'United Arab Emirates' },
      { sortname: 'GB', name:  'United Kingdom' },
      { sortname: 'US', name:  'United States' },
      { sortname: 'UM', name:  'United States Minor Outlying Islands' },
      { sortname: 'UY', name:  'Uruguay' },
      { sortname: 'UZ', name:  'Uzbekistan' },
      { sortname: 'VU', name:  'Vanuatu' },
      { sortname: 'VA', name:  'Vatican City State (Holy See)'},
      { sortname: 'VE', name:  'Venezuela' },
      { sortname: 'VN', name:  'Vietnam' },
      { sortname: 'VG', name:  'Virgin Islands (British)' },
      { sortname: 'VI', name:  'Virgin Islands (US)' },
      { sortname: 'WF', name:  'Wallis And Futuna Islands' },
      { sortname: 'EH', name:  'Western Sahara' },
      { sortname: 'YE', name:  'Yemen' },
      { sortname: 'YU', name:  'Yugoslavia' },
      { sortname: 'ZM', name:  'Zambia' },
      { sortname: 'ZW', name:  'Zimbabwe' }
    ])
  end
end
